// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqxbbhftxqidyshrmzkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeGJiaGZ0eHFpZHlzaHJtemt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Nzc4NTgsImV4cCI6MjA2NzM1Mzg1OH0.msd2-TBIkqOkdBXvxyKiuly0FtArogvODsY3MYx7l-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});